Configure signing workflow

diff --git a/.github/workflows/publish_stage.yml b/.github/workflows/publish_stage.yml
--- a/.github/workflows/publish_stage.yml
+++ b/.github/workflows/publish_stage.yml
@@ -7,41 +7,67 @@ jobs:
     name: publish
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
       - name: Setup .NET
-        uses: actions/setup-dotnet@v3
+        uses: actions/setup-dotnet@v4
         with:
           dotnet-version: 6.0.x
+
+      - name: Get current datetime
+        id: datetime
+        run: echo "datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
       
       - name: Build
         run: dotnet build -c Release src/GroupDocs.Metadata.Cli/GroupDocs.Metadata.Cli.csproj
       
       - name: Pack
-        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/GroupDocs.Metadata.Cli/GroupDocs.Metadata.Cli.csproj -o .
-
-      - name: Write cert
-        env:
-          PFX_IN_BASE64: ${{ secrets.PFX_IN_BASE64 }}
-          PFX_PATH: ${{ secrets.PFX_PATH }}
-        run: echo "${PFX_IN_BASE64}" | base64 --decode > ${PFX_PATH}
+        run: 
+          dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg -p:VersionSuffix=alpha-${{ env.datetime }} --no-build -c Release src/GroupDocs.Metadata.Cli/GroupDocs.Metadata.Cli.csproj -o ./build_out
       
-      - name: Sign
-        env: 
-          PFX_PATH: ${{ secrets.PFX_PATH }}
-          PFX_PWD: ${{ secrets.PFX_PWD }}
-          PFX_TMS: ${{ secrets.PFX_TMS }}
-        run: dotnet nuget sign *.nupkg --certificate-path ${PFX_PATH} --certificate-password ${PFX_PWD} --timestamper ${PFX_TMS} 
+      - name: Download CodeSignTool
+        run: |
+          wget -O codesign.zip https://github.com/SSLcom/CodeSignTool/releases/download/v1.3.0/CodeSignTool-v1.3.0.zip
+      
+      - name: Unpack CodeSignTool
+        run: |
+          mkdir -p ./code_sign
+          unzip -q codesign.zip -d ./code_sign
+      
+      - name: Configure CodeSignTool
+        run: |
+          confPath="./code_sign/conf/code_sign_tool.properties"
+          if [ -f "$confPath" ]; then rm -f "$confPath"; fi
+          cat > "$confPath" << EOF
+          CLIENT_ID=kaXTRACNijSWsFdRKg_KAfD3fqrBlzMbWs6TwWHwAn8
+          OAUTH2_ENDPOINT=https://login.ssl.com/oauth2/token
+          CSC_API_ENDPOINT=https://cs.ssl.com
+          TSA_URL=http://ts.ssl.com
+          TSA_LEGACY_URL=http://ts.ssl.com/legacy
+          EOF
 
-      - name: Verify
-        run: dotnet nuget verify *.nupkg
+      - name: Prepare artifacts directory
+        run: |
+          mkdir -p ./artifacts
+          find ./build_out -type f ! -name "*.nupkg" -exec mv {} ./artifacts/ \; 2>/dev/null || true
 
-      - name: Remove cert
-        env: 
-           PFX_PATH: ${{ secrets.PFX_PATH }}
-        run: rm $PFX_PATH
-        
+      - name: Sign packages with SSL.com eSigner
+        working-directory: ${{ github.workspace }}/code_sign
+        env:
+          ES_USERNAME: ${{ secrets.ES_USERNAME }}
+          ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
+          ES_TOTP_SECRET: ${{ secrets.ES_TOTP_SECRET }}
+        run: |
+          java -Xmx1024M -jar "./jar/code_sign_tool-1.3.0.jar" batch_sign -username="$ES_USERNAME" -password="$ES_PASSWORD" -totp_secret="$ES_TOTP_SECRET" -input_dir_path="../build_out" -output_dir_path="../artifacts"
+   
       - name: Publish
         env:
           NUGET_TOKEN: ${{ secrets.NUGET_API_KEY_STAGE }}
-        run: dotnet nuget push *.nupkg -s https://apiint.nugettest.org/v3/index.json -k ${NUGET_TOKEN} --skip-duplicate 
+        run: dotnet nuget push ./artifacts/*.nupkg -s https://apiint.nugettest.org/v3/index.json -k ${NUGET_TOKEN} --skip-duplicate 
+
+      - name: Upload logs or outputs
+        uses: actions/upload-artifact@v4
+        if: always()  # Ensures artifacts are uploaded even if the job fails
+        with:
+          name: nuget-packages
+          path: ./artifacts/*.nupkg        
